### ISSUE TITLE
MIMIC dataset sample and ESDR dataset 

### ISSUE THREAD

**Issue by huangtao36** [v1xerunt/StageNet#1]
Great job. Can this code be applied to the ESDR data set, and where can I find this ESDR dataset? And, can you provide some test samples, and annotate the data flow in your code in detail.

**Comment by v1xerunt** [comment]
Thank you for your interest in our work. 

1. ESRD dataset is collected from our cooperating hospital. Unfortunately, we are currently not allowed to release them.

2. For MIMIC-III benchmark datasets, we use exactly the same data pre-processing code in https://github.com/YerevaNN/mimic3-benchmarks/. We also added some train/test samples in our repo.

3. If you want to apply our model on your own EHR dataset, you need to re-implement the train.py. You should feed the model with two inputs: EHR records with shape (batch_size, time_step, feature_dim) and time intervals between visits with shape (batch_size, time_step, 1).

**Comment by huangtao36** [comment]
@v1xerunt Thanks.
