### ISSUE TITLE
Purpose of "decomp_normalizer" and "demographic" folder in jupyter notebook

### ISSUE THREAD

**Issue by sarwart** [v1xerunt/StageNet#4]
Hi!

What is the purpose of "decomp_normalizer"? Is the provided file a standard for the complete dataset?

Also, the jupyter notebook contains a reference to "demographic" folder. The data generated using "https://github.com/YerevaNN/mimic3-benchmarks" does not generate any demographic folder and I am not sure which csv files are being referred for this case. Can you please explain?

Tabinda

**Comment by v1xerunt** [comment]
Hi, the decomp_normalizer is a normalizer generated by the original benchmark dataset, which is used to normalize the features. You can also use the benchmark code to get this file.

The demographic folder saves the patients' demographic data (age, gender, race...). We observe that using demographic data can improve the performance, but we don't use them in our model and baseline models. So you can just ignore the demographic-related codes. If you want to use these data, you can extract them from the csvs generated by the benchmark code using patient id.
